/**
 * Planning action and optimization result types.
 *
 * These types represent AI-suggested planning actions before they are validated
 * and applied. The AI works with indices into deterministic candidate slot lists
 * — it cannot invent arbitrary times, so all scheduling actions point back into
 * a validated candidate array that the orchestrator controls.
 */

// ── Enriched candidate slot ───────────────────────────────────────────────────

/**
 * A deterministically validated time slot with rich metadata for AI context.
 * Candidates are generated by the scheduler; the AI only selects among them.
 *
 * The `taskId` field serves dual purpose:
 *   - For task-scheduling candidates: the task this slot was generated for
 *   - For movable-block destination candidates: the block ID being relocated
 *     (prefix convention: block IDs are "block-*", task IDs are "task-*")
 */
export interface EnrichedCandidateSlot {
  /** Task ID (or block ID for movable-block destinations) this slot was generated for */
  taskId: string
  date: string
  startTime: string   // HH:MM
  endTime: string     // HH:MM
  durationMinutes: number
  /** Total minutes of blocks already scheduled on this day */
  dayWorkloadMinutes: number
  /** How well this slot's time matches the task's energy type */
  energyAlignment: 'perfect' | 'partial' | 'none'
  /** Whether this slot falls on or before the task's due date */
  urgencyFit: 'before-due' | 'on-due' | 'after-due' | 'no-deadline'
  /** Whether this slot is fully inside a preferred focus window (09:00–12:00 or 13:30–16:00) */
  isFocusWindow: boolean
  /** Composite score — higher is better (used for deterministic ranking and AI context) */
  score: number

  // ── Enhanced metadata (v2) ────────────────────────────────────────────────

  /**
   * 0–1 premium focus-window quality score.
   * 1.0 = perfect alignment with deep-work prime hours (09:00–12:00 morning block).
   * 0.0 = no alignment.
   * More granular than the binary `isFocusWindow`.
   */
  focusQuality: number

  /**
   * Cost of placing something in this slot, on a 0–2 scale:
   *   0 = slot is freely available
   *   1 = placing here displaces a flexible block (moderate disruption)
   *   2 = placing here displaces something important (high disruption)
   * Non-zero values also set `displacedBlockId`.
   */
  displacementCost: number

  /** Block ID of the flexible block that would be displaced, if any. */
  displacedBlockId?: string

  /**
   * True when this candidate is a split-chunk slot — shorter than the task's
   * full `durationMinutes`. Carries `chunkDurationMinutes` as the actual chunk size.
   */
  isChunkSlot: boolean

  /** Duration this chunk slot was generated for (only set when isChunkSlot). */
  chunkDurationMinutes?: number

  /**
   * True when this slot is a destination candidate for a movable block
   * (taskId holds the block ID, not a task ID).
   */
  isBlockDestination: boolean
}

// ── Planning actions ───────────────────────────────────────────────────────────

/** AI schedules an unscheduled task into a validated candidate slot */
export interface ActionScheduleTask {
  type: 'schedule_task'
  taskId: string
  /** 0-based index into OptimizeDayResult.candidateSlots */
  candidateIndex: number
  rationale: string
}

/** AI suggests moving a flexible (unlocked) block to a validated candidate slot */
export interface ActionMoveBlock {
  type: 'move_block'
  blockId: string
  /** 0-based index into OptimizeDayResult.candidateSlots */
  candidateIndex: number
  rationale: string
}

/** AI suggests deferring a task's due date */
export interface ActionDeferTask {
  type: 'defer_task'
  taskId: string
  toDate: string   // YYYY-MM-DD — must be in the future
  rationale: string
}

/** AI suggests locking a block to protect it from future rebuilds */
export interface ActionLockBlock {
  type: 'lock_block'
  blockId: string
  rationale: string
}

/** AI flags a risk — informational only, no state change */
export interface ActionFlagRisk {
  type: 'flag_risk'
  entityId: string
  message: string
}

/**
 * AI suggests splitting a long task into multiple shorter blocks placed in
 * separate candidate slots.
 *
 * Implementation: Option A — one canonical task, multiple linked blocks.
 * The task keeps its original `durationMinutes` (total). Each chunk block
 * has a shorter `duration` and the same `linkedTaskId`. `task.scheduled`
 * becomes true; `task.linkedCalendarBlockIds` contains every chunk block ID and
 * `task.linkedCalendarBlockId` continues to point to the first chunk for
 * compatibility with older UI code.
 *
 * At least 2 chunks are required. candidateIndex fields reference the flat
 * candidate pool and MUST point to `isChunkSlot: true` candidates tagged for
 * this task. The sum of chunk durations should approximate task.durationMinutes.
 */
export interface ActionSplitTask {
  type: 'split_task'
  taskId: string
  chunks: Array<{
    /** Duration for this individual chunk in minutes (15–240) */
    durationMinutes: number
    /** 0-based index into OptimizeDayResult.candidateSlots — must be a chunk slot */
    candidateIndex: number
  }>
  rationale: string
}

/**
 * Suggests reserving an unoccupied focus window to protect it from being
 * consumed by low-value tasks. On apply: creates a locked `focus` type block.
 *
 * This is primarily AI-generated, but also produced by the deterministic
 * fallback when a premium deep-work window is detected as unused.
 */
export interface ActionProtectFocusWindow {
  type: 'protect_focus_window'
  date: string       // YYYY-MM-DD
  startTime: string  // HH:MM
  endTime: string    // HH:MM
  rationale: string
}

/**
 * Suggests explicitly preserving a scheduled block by locking it.
 * Semantically distinct from lock_block: preserve_block is proactively
 * generated when the optimizer determines a block is valuable and should be
 * protected from future rebuilds or displacement.
 *
 * On apply: sets block.locked = true (same execution as lock_block).
 */
export interface ActionPreserveBlock {
  type: 'preserve_block'
  blockId: string
  rationale: string
}

export type PlanningAction =
  | ActionScheduleTask
  | ActionMoveBlock
  | ActionDeferTask
  | ActionLockBlock
  | ActionFlagRisk
  | ActionSplitTask
  | ActionProtectFocusWindow
  | ActionPreserveBlock

// ── Optimization results ───────────────────────────────────────────────────────

export interface OptimizeDayResult {
  date: string
  /** Validated actions only — invalid actions are stripped before returning */
  actions: PlanningAction[]
  /**
   * Full candidate slot list used during this optimization pass.
   * candidateIndex fields in actions are 0-based indices into this array.
   */
  candidateSlots: EnrichedCandidateSlot[]
  summary: string
  confidence: number   // 0–1
  source: 'ai' | 'fallback'
  warnings: string[]
}

export interface OptimizeWeekResult {
  weekStart: string
  /** All validated actions across the entire week */
  actions: PlanningAction[]
  /** Per-day results — each has its own candidateSlots array */
  dayResults: OptimizeDayResult[]
  summary: string
  confidence: number   // 0–1
  source: 'ai' | 'fallback'
  warnings: string[]
}
